config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match "/delayed_job" => BetterDelayedJobWeb, :anchor => false, :via => [:get, :post]

  resources :delayed_jobs
  resources :favorites
  resources :notifications
  resources :sys_configs
  resources :sys_logs do
    get :search, on: :collection
  end

  resources :features do
    get :list, :on => :collection
    get :role_features_grid, :on => :member
    get :add_features, :on => :member
    get :add_features_submit, :on => :member
    delete :remove_feature_from_role, :on => :member
  end

  resources :roles do
    get :role_users_grid, :on => :member
    get :add_users, :on => :member
    get :add_users_submit, :on => :member
    delete :remove_user_from_role, :on => :member
  end

  resources :departments do
    resources :department_docs
    get :department, :on => :member
    get :add_users, :on => :member
    get :add_users_submit, :on => :member
    delete :remove_user_from_department, :on => :member
  end
  resources :users do
    get :reset_password, :on => :member
    get :edit_password, :on => :member
    post :update_password, :on => :member
    get :list, on: :collection
    get :show_api_key, on: :member
    post :generate_api_key, on: :member
  end

  resources :session do
    get :ao, on: :collection
    get :aologin, on: :collection
    post :aosignin, on: :collection
  end

  resources :book_codes do
    collection do
      post :generate_book_codes
    end
  end

  resources :grades do
    member do
      get :subjects
    end
    resources :subjects do
      resources :courses
      delete :destroy_detail_imgs, on: :member
      get :generate_qr_code_image, on: :member
    end
  end

  resources :static_images do
    collection do
      get :play
    end
  end

  namespace :api do
    namespace :v1 do
      resources :main_page, only: [] do
        collection do
          get :top_video
          get :subjects
        end
      end

      resources :video, only: [] do
        collection do
          get :play
        end
      end

      resources :courses, only: [] do
        collection do
          get :data
        end
      end

      resources :subjects, only: [:show] do
        collection do
          get :check_subject_owner
          get :my_subjects
          get :search
        end
      end

      resources :wechats, only: [] do
        get :wechat_auth, on: :collection
      end

      resources :feedbacks, only: [:create]
      resources :book_codes, only: [:create]
      resources :setting, only: [] do
        collection do
          get :user_agreement
          get :privacy_policy
        end
      end

      resources :text_settings, only: [] do
        collection do
          get :book_code_comment
        end
      end
    end
  end

  resources :customers, only: [:index]
  resources :feedbacks
  resources :text_settings

  post 'areas/cities'
  post 'areas/districts'

  get 'login' => 'session#new', as: :login
  get 'logout' => 'session#destroy', as: :logout

  root 'session#index'
end

app/models/static_image.rb
class StaticImage < ApplicationRecord
  enum img_type: %i[main_page_video courses_page_banner user_agreement privacy_policy main_page_banner]
  # enum img_type: %i[main_page_video courses_page_banner user_agreement privacy_policy]
  has_one_attached :img
end

app/controllers/static_images_controller.rb
class StaticImagesController < ApplicationController
  before_action :set_static_image, only: [:show, :edit, :update, :destroy]

  # GET /static_images
  # GET /static_images.json
  def index
    @static_images = initialize_grid( StaticImage, per_page: 20,
                                                   order_direction: 'asc',
                                                   name: 'static_images',
                                                   enable_export_to_csv: true,
                                                   csv_file_name: 'static_images' )
  end

  # GET /static_images/1
  # GET /static_images/1.json
  def show
  end

  # GET /static_images/new
  def new
    @static_image = StaticImage.new
  end

  # GET /static_images/1/edit
  def edit
  end

  # POST /static_images
  # POST /static_images.json
  def create
    @static_image = StaticImage.new(static_image_params)

    respond_to do |format|
      if @static_image.save
        format.html { redirect_to static_images_url, notice: 'Static image was successfully created.' }
        format.json { render :show, status: :created, location: @static_image }
      else
        format.html { render :new }
        format.json { render json: @static_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_images/1
  # PATCH/PUT /static_images/1.json
  def update
    respond_to do |format|
      if @static_image.update(static_image_params)
        format.html { redirect_to static_images_url, notice: 'Static image was successfully updated.' }
        format.json { render :show, status: :ok, location: @static_image }
      else
        format.html { render :edit }
        format.json { render json: @static_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_images/1
  # DELETE /static_images/1.json
  def destroy
    @static_image.destroy
    respond_to do |format|
      format.html { redirect_to static_images_url, notice: 'Static image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_image
      @static_image = StaticImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_image_params
      params.require(:static_image).permit(:img_type, :order_no, :img)
    end
end

app/helpers/static_images_helper.rb
module StaticImagesHelper
end

app/views/static_images/_form.html.slim
= simple_form_for(@static_image) do |f|
  - if @static_image.errors.any?
    #error_explanation.alert.alert-warning
      h4
        | 该资源保存时出错：
        = pluralize(@grade.errors.count, "个错误")
      ul
        - @grade.errors.full_messages.each do |message|
          li
            = message
  .form-inputs
    small#emailHelp.form-text.text-muted 学习页面banner: 分辨率(高*宽 单位px)：282 * 750
    small#emailHelp.form-text.text-muted 主页面banner:   分辨率(高*宽 单位px)：282 * 750
    small#emailHelp.form-text.text-muted 用户协议:       分辨率(高*宽 单位px)：auto * 650
    small#emailHelp.form-text.text-muted 隐私条款:       分辨率(高*宽 单位px)：auto * 650
    hr
    = f.input :img_type, label: '文件类型', as: :select, collection: StaticImage.img_type_options
    = f.input :order_no, label: '顺序号'
    = f.input :img, label: '上传文件', as: :file
  .form-actions
    = f.button :submit, '确认', class: 'btn btn-success'

app/views/static_images/_static_images_grid.html.erb
<%= grid(@static_images, show_filters: :when_filtered, hide_csv_button: true) do |g|
  g.column name: '顺序号', attribute: 'order_no', ordering: false
  g.column name: '图片或视频类型', attribute: 'img_type', ordering: false do |static_image|
    static_image.img_type_name
  end

  g.column name: '图片或视频', attribute: 'img_type', ordering: false, filter: false do |static_image|
    case static_image.img_type
    when 'main_page_video'
        static_image.img.attached? ? (video_tag( static_url_for(static_image.img), controls: true, preload: 'none', size: '300x170')) : '暂无视频'
    else
        static_image.img.attached? ? (image_tag  static_url_for(static_image.img), style: 'width: 100px; height: 50px', class: 'image-modal') : '暂无图片'
    end
  end

  g.column in_csv: false, html: {style: "width:15px;"}  do |static_image|
    if can?("static_images", "edit") && can_sys?(static_image)
      link_to '编辑', edit_static_image_path(static_image), class: 'btn btn-secondary btn-sm'
    end
  end

  g.column in_csv: false, html: {style: "width:15px;"}  do |static_image|
    if can?("static_images", "destroy") && can_sys?(static_image)
      link_to '删除', static_image, method: :delete, data: { confirm: '您确认删除吗？' }, class: 'btn btn-danger btn-sm'
    end
  end
end -%>

app/views/static_images/edit.html.slim
= link_to '返回', static_images_path, class: 'btn btn-primary mb-2'
.card
  .card-header
    .card-title 新建图片
  .card-body
    = render 'form'

app/views/static_images/index.html.slim
.card
  .card-header
    .card-title 图片视频管理
  .card-body
    .row
      = link_to '新建图片', new_static_image_path, class: 'btn btn-primary mb-2'
      = render partial: "static_images_grid"

app/views/static_images/new.html.slim
= link_to '返回', static_images_path, class: 'btn btn-primary mb-2'
.card
  .card-header
    .card-title 编辑图片视频
  .card-body
    = render 'form'

app/views/static_images/show.html.slim
p#notice = notice

p
  strong Img type:
  = @static_image.img_type
p
  strong Order no:
  = @static_image.order_no

=> link_to 'Edit', edit_static_image_path(@static_image)
'|
=< link_to 'Back', static_images_path