config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match "/delayed_job" => BetterDelayedJobWeb, :anchor => false, :via => [:get, :post]

  resources :delayed_jobs
  resources :favorites
  resources :notifications
  resources :sys_configs
  resources :sys_logs do
    get :search, on: :collection
  end

  resources :features do
    get :list, :on => :collection
    get :role_features_grid, :on => :member
    get :add_features, :on => :member
    get :add_features_submit, :on => :member
    delete :remove_feature_from_role, :on => :member
  end

  resources :roles do
    get :role_users_grid, :on => :member
    get :add_users, :on => :member
    get :add_users_submit, :on => :member
    delete :remove_user_from_role, :on => :member
  end

  resources :departments do
    resources :department_docs
    get :department, :on => :member
    get :add_users, :on => :member
    get :add_users_submit, :on => :member
    delete :remove_user_from_department, :on => :member
  end
  resources :users do
    get :reset_password, :on => :member
    get :edit_password, :on => :member
    post :update_password, :on => :member
    get :list, on: :collection
    get :show_api_key, on: :member
    post :generate_api_key, on: :member
  end

  resources :session do
    get :ao, on: :collection
    get :aologin, on: :collection
    post :aosignin, on: :collection
  end

  resources :book_codes do
    collection do
      post :generate_book_codes
    end
  end

  resources :grades do
    member do
      get :subjects
    end
    resources :subjects do
      resources :courses
      delete :destroy_detail_imgs, on: :member
      get :generate_qr_code_image, on: :member
    end
  end

  resources :static_images do
    collection do
      get :play
    end
  end

  namespace :api do
    namespace :v1 do
      resources :main_page, only: [] do
        collection do
          get :top_video
          get :subjects
        end
      end

      resources :video, only: [] do
        collection do
          get :play
        end
      end

      resources :courses, only: [] do
        collection do
          get :data
        end
      end

      resources :subjects, only: [:show] do
        collection do
          get :check_subject_owner
          get :my_subjects
          get :search
        end
      end

      resources :wechats, only: [] do
        get :wechat_auth, on: :collection
      end

      resources :feedbacks, only: [:create]
      resources :book_codes, only: [:create]
      resources :setting, only: [] do
        collection do
          get :user_agreement
          get :privacy_policy
        end
      end

      resources :text_settings, only: [] do
        collection do
          get :book_code_comment
        end
      end
    end
  end

  resources :customers, only: [:index]
  resources :feedbacks
  resources :text_settings

  post 'areas/cities'
  post 'areas/districts'

  get 'login' => 'session#new', as: :login
  get 'logout' => 'session#destroy', as: :logout

  root 'session#index'
end

app/models/user.rb
# -*- encoding : utf-8 -*-
require 'digest/sha2'

# User类为后台管理用的用户
class User < ApplicationRecord
  # 宏
  attr_accessor :password_confirmation
  attr_reader   :password

  # 验证
  validates :login, presence: true, uniqueness: true, length: {minimum: 1, maximum: 50}
  validates :name, length: { maximum: 20 }
  validates :email, length: { maximum: 100 }, format: { with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i }, allow_nil: true, allow_blank: true
  validates :gender, length: {maximum: 10}
  validates :mobile_phone, length: { maximum: 100}
  validates :password, confirmation: true
  validates :password, presence:true, on: :create
  validates :password, length: { minimum: 6, maximum: 20 }, allow_nil: true
  validates :department_id, presence: false
  validate  :password_must_be_present

  # 关联organization_empty
  has_many   :user_roles, dependent: :delete_all
  has_many   :roles, :through => :user_roles
  has_many   :notifications
  has_many   :sys_logs
  has_many   :favorites

  # 所有具有某一权限的用户集合
  def self.has_approval_role(action)
    sql = "SELECT DISTINCT users.* FROM users " +
          "INNER JOIN user_roles ON users.id = user_roles.user_id " +
          "INNER JOIN roles ON user_roles.role_id = roles.id " +
          "INNER JOIN role_features ON roles.id = role_features.role_id " +
          "INNER JOIN features ON role_features.feature_id = features.id " +
          "WHERE features.action_names = '#{action}' "
    find_by_sql(sql)
  end

  # 用户登录验证方法
  def User.authenticate(login, password)
    if user = find_by_login(login)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  # 用户密码加密方法
  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "shike" + salt)
  end

  # 'password'作为虚拟属性
  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end

  # 用于SAML登录密码验证
  def valid_password?(password)
    if self.hashed_password == User.encrypt_password(password, self.salt)
      true
    else
      false
    end
  end

  # 是否是平台管理员
  def admin?
    if self.login == 'admin'
      true
    else
      false
    end
  end

  private

  def password_must_be_present
    errors.add(:password, "缺少密码") unless hashed_password.present?
  end

  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  layout 'system', except: [:edit_password]

  skip_before_action :can, only: [:edit_password, :update_password]
  before_action :set_user, only: [:edit, :update, :destroy, :reset_password, :update_password]
  after_action :make_log, only: [:create, :update, :destroy, :reset_password, :update_password]

  # 管理员进入“用户管理”功能，系统显示用户查询列表页面。
  # 管理员可以输入关键字进行搜索，可与对列表进行排序，列表应该进行分页显示。
  # 页面中醒目显示“新建用户”按钮；针对每一个用户，页面上显示：查看、编辑、禁用/启用、删除按钮。
  def index
    if admin?
      @users = initialize_grid( User, per_page: 20,
                                order: 'sort_no', order_direction: 'asc',
                                name: 'users',
                                enable_export_to_csv: true, csv_file_name: 'users' )
    else
      @users = initialize_grid( User, per_page: 20,
                                conditions: { organization_id: @current_user.organization.try(:id) },
                                order: 'sort_no', order_direction: 'asc',
                                name: 'users',
                                enable_export_to_csv: true, csv_file_name: 'users' )
    end
    export_grid_if_requested
  end

  # 用户查看某一个用户的详细信息
  def show
    @user = User.find(params[:id])
  end

  # 管理员在用户列表页面中点击“新建用户”按钮，系统显示新建用户表单页面。
  def new
    @user = User.new
  end

  # 针对用户列表中的某一个用户，管理员点击“编辑”按钮，系统显示该用户信息的编辑页面。
  def edit
  end

  # 管理员填写新用户之后点击“提交”按钮，系统保存新用户信息并返回用户列表页面。
  def create
    @user = User.new(user_params.merge({:password => '123456@Shike', :password_confirmation => '123456@Shike'}))

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: '新建用户成功啦，默认密码是 123456@Shike' }
      else
        format.html { render :new }
      end
    end
  end

  # 管理员修改该用户信息之后，点击保存按钮，系统保存该用户信息，并返回用户列表页面。
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: '用户信息已经成功保存了' }
      else
        format.html { render :edit }
      end
    end
  end

  # 针对用户列表中的某一个用户，管理员点击“删除”按钮，系统弹出确认对话框要求用户进行确认。
  # 在管理员确认之后，系统删除该用户信息并返回用户列表页面。
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '该用户已经被删除了' }
    end
  end

  # 管理员将用户的密码初始化成为123456
  def reset_password
    respond_to do |format|
      if @user.update_attributes({:password => '123456@Shike', :password_confirmation => '123456@Shike', :changed_password => false})
        format.html { redirect_to users_url, notice: '用户已经重置成为123456@Shike' }
      else
        format.html { render :index }
      end
    end
  end

  # 用户点击系统右上角个人设置菜单中的“修改密码”菜单项，系统显示修改密码页面。
  def edit_password
    @user = User.find_by_id(@current_user&.id)
  end

  # 用户填写原密码和新密码之后，提交，系统修改用户密码。
  def update_password
    # byebug
    @searhc_user = User.authenticate(@user.login, params[:old_password])
    # byebug
    if @searhc_user.nil?
      redirect_to edit_password_user_path, notice: '原始密码不正确'
    elsif @user.update_attributes({:password => params[:password], :password_confirmation => params[:password_confirmation], :changed_password => true})
      # redirect_to edit_password_user_path, notice: '密码已经修改成功了'
      redirect_to "/", notice: "密码已经修改成功了！如果您是第一次登录本系统，请联系系统管理员要求给自己开通权限。"
    else
      render :edit_password
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:login, :name, :email,
                                 :hashed_password, :password, :password_confirmation,
                                 :department_id,
                                 :sort_no,
                                 :gender,
                                 :mobile_phone,
                                 :organization_id)
  end
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/users/_edit_password_form.html.slim
= form_tag "/users/#{@current_user&.id}/update_password", class: 'form-horizontal mt-5', wrapper: :horizontal_form do
  .form-group
    label.form-label
      | 原始密码
    = password_field_tag :old_password, params[:old_password], class: "form-control"
  .form-group
    label.form-label
      | 新密码
    = password_field_tag :password, params[:password], class: "form-control"
    span#helpBlock.help-block
      | 密码必须最少包含8个字符，并且需要同时包含大写字母、小写字母、数字和标点符号
  .form-group
    label.form-label
      | 再输入一次新密码
    = password_field_tag :password_confirmation, params[:password_confirmation], class: "form-control"
  = submit_tag("保存", class: "btn btn-success")

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation.alert.alert-warning
      h4
        | 该角色保存时出错：
        = pluralize(@user.errors.count, "个错误")
      ul
        - @user.errors.full_messages.each do |message|
          li
            = message
  .form-inputs
    = f.input :login, label: '用户名'
    = f.input :name, label: '姓名'
    = f.input :gender, collection: USER_GENDER, label: '性别'
    = f.input :mobile_phone, label: '手机号'
    = f.input :email, label: '邮箱'
  .form-actions
    = f.button :submit, '确认', class: 'btn btn-success'

app/views/users/_users_grid.html.erb
<%= grid(@users, show_filters: :when_filtered) do |g|
  g.column name: '登录名', attribute: 'login', ordering: false do |user|
    user.login
  end
  g.column name: '真实姓名', attribute: 'name', ordering: false, in_csv: false do |user|
    user.name
  end

  g.column name: '真实姓名', attribute: 'name', in_html: false do |user|
    user.name
  end

  g.column name: '所属角色', ordering: false do |user|
    user.roles.map{ |r| r.name }.join(', ')
  end

  g.column in_csv: false, html: {style: "width:15px;"}  do |user|
    if can?("users", "edit") && can_sys?(user)
      link_to '编辑', edit_user_path(user), class: 'btn btn-secondary btn-sm'
    end
  end

  g.column in_csv: false, html: {style: "width:15px;"}  do |user|
    if can?("users", "edit") && can_sys?(user)
      link_to '重置', reset_password_user_path(user), data: {confirm: '您确认要重置该用户的密码为123456@Shike吗？' }, class: 'btn btn-secondary btn-sm'
    end
  end

  g.column in_csv: false, html: {style: "width:15px;"}  do |user|
    if can?("users", "destroy") && can_sys?(user)
      link_to '删除', user, method: :delete, data: { confirm: '您确认删除吗？' }, class: 'btn btn-danger btn-sm'
    end
  end
end -%>

app/views/users/edit.html.slim
= link_to '返回', users_path, class: 'btn btn-primary mb-2'
.card
  .card-header
    .card-title 编辑用户
  .card-body
    = render 'form'

app/views/users/edit_password.html.slim
.card
  .card-header
    .card-title 修改密码
  .card-body
    = render 'edit_password_form'

app/views/users/index.html.slim
.row
  .card
    .card-header
      h3.card-title 用户管理
      = link_to '新建用户', new_user_path, class: 'btn btn-primary', style: 'margin-left: auto' if can?("users", "new")
    .card-body
      .row
        .btn-group.btn-group-sm role="group" aria-label="..."
          button class="btn btn-primary btn-sm wg-external-submit-button" data-grid-name='users' 过滤
          button class="btn btn-secondary btn-sm wg-external-reset-button" data-grid-name='users' 清除过滤条件
      .row
        .table-responsive
          = render partial: "users_grid", :locals => {users: @users}

app/views/users/new.html.slim
= link_to '返回', users_path, class: 'btn btn-primary mb-2'
.card
  .card-header
    .card-title 新建用户
  .card-body
    = render 'form'

app/views/users/show.html.slim
#content
  .container-fluid
    = get_bread_crumb
    = get_notice_bar
    .row
      .col-sm-12
        .btn-group.btn-group-sm role="group"
          = link_to '返回', session[:bread][-2]["url_str"], class: "btn btn-default"
          = link_to '编辑', edit_user_path(@user), class: "btn btn-default" if can?("users", "edit") && can_sys?(@user)
    .row
      .col-sm-3
        p.text-right
          strong 登录名&nbsp;
      .col-sm-3
        = @user.login
      .col-sm-2
        p.text-right
          strong 顺序号&nbsp;
      .col-sm-3
        = @user.sort_no
    .row
      .col-sm-3
        p.text-right
          strong 中文姓名&nbsp;
      .col-sm-3
        = @user.name
      .col-sm-2
        p.text-right
          strong 英文姓名&nbsp;
      .col-sm-3
        = @user.english_name
    .row
      .col-sm-3
        p.text-right
          strong 人员编码&nbsp;
      .col-sm-3
        = @user.code
      .col-sm-2
        p.text-right
          strong 政治面貌&nbsp;
      .col-sm-3
        = @user.politics_status
    .row
      .col-sm-3
        p.text-right
          strong 证件类型&nbsp;
      .col-sm-3
        = @user.id_type
      .col-sm-2
        p.text-right
          strong 证件号码&nbsp;
      .col-sm-3
        = @user.id_card_no
    .row
      .col-sm-3
        p.text-right
          strong 性别&nbsp;
      .col-sm-3
        = @user.gender
      .col-sm-2
        p.text-right
          strong 婚姻状况&nbsp;
      .col-sm-3
        = @user.marital_status
    .row
      .col-sm-3
        p.text-right
          strong 最高学历&nbsp;
      .col-sm-3
        = @user.top_education
      .col-sm-2
        p.text-right
          strong 最高学位&nbsp;
      .col-sm-3
        = @user.top_degree
    .row
      .col-sm-12
        hr
    .row
      .col-sm-3
        p.text-right
          strong 现任职务&nbsp;
      .col-sm-3
        = @user.position
      .col-sm-2
        p.text-right
          strong 职级&nbsp;
      .col-sm-3
        = @user.rank
    .row
      .col-sm-3
        p.text-right
          strong 所属部门&nbsp;
      .col-sm-3
        = @user.department.name if @user.department
      .col-sm-2
        p.text-right
          strong 所属单位&nbsp;
      .col-sm-3
        = @user.orgnization_name
    .row
      .col-sm-12
        hr
    .row
      .col-sm-3
        p.text-right
          strong 办公电话&nbsp;
      .col-sm-3
        = @user.work_phone
      .col-sm-2
        p.text-right
          strong 办公传真&nbsp;
      .col-sm-3
        = @user.work_fax
    .row
      .col-sm-3
        p.text-right
          strong 家庭电话&nbsp;
      .col-sm-3
        = @user.home_phone
      .col-sm-2
        p.text-right
          strong 移动电话&nbsp;
      .col-sm-3
        = @user.mobile_phone
    .row
      .col-sm-3
        p.text-right
          strong EMAIL地址&nbsp;
      .col-sm-3
        = @user.email
      .col-sm-2
        p.text-right
          strong EMAIL地址2&nbsp;
      .col-sm-3
        = @user.email2
    .row
      .col-sm-3
        p.text-right
          strong 国家&nbsp;
      .col-sm-3
        = @user.country
      .col-sm-2
        p.text-right
          strong 邮政编码&nbsp;
      .col-sm-3
        = @user.zip_code
    .row
      .col-sm-3
        p.text-right
          strong 省&nbsp;
      .col-sm-3
        = @user.province
      .col-sm-2
        p.text-right
          strong 城市&nbsp;
      .col-sm-3
        = @user.city
    .row
      .col-sm-3
        p.text-right
          strong 通信地址&nbsp;
      .col-sm-9
        = @user.address
    .row
      .col-sm-12
        hr
    .row
      .col-sm-3
        p.text-right
          strong 备注&nbsp;
      .col-sm-9
        = simple_format @user.memo
    

app/views/users/show_api_key.html.slim
#content
  .container-fluid
    = get_bread_crumb
    = get_notice_bar
    .row
      .col-sm-12
        .btn-group.btn-group-sm role="group"
          = link_to '返回', session[:bread][-2]["url_str"], class: "btn btn-default"
          = link_to '生成新的API接口键值', generate_api_key_user_path(@current_user), class: "btn btn-primary", method: 'post' if can?("users", "generate_api_key")
    .row
      .col-sm-3
        p.text-right
          strong 当前的API接口键值：&nbsp;
      .col-sm-9
        = @current_user.api_key.to_s
    