config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match "/delayed_job" => BetterDelayedJobWeb, :anchor => false, :via => [:get, :post]

  resources :delayed_jobs
  resources :favorites
  resources :notifications
  resources :sys_configs
  resources :sys_logs do
    get :search, on: :collection
  end

  resources :features do
    get :list, :on => :collection
    get :role_features_grid, :on => :member
    get :add_features, :on => :member
    get :add_features_submit, :on => :member
    delete :remove_feature_from_role, :on => :member
  end

  resources :roles do
    get :role_users_grid, :on => :member
    get :add_users, :on => :member
    get :add_users_submit, :on => :member
    delete :remove_user_from_role, :on => :member
  end

  resources :departments do
    resources :department_docs
    get :department, :on => :member
    get :add_users, :on => :member
    get :add_users_submit, :on => :member
    delete :remove_user_from_department, :on => :member
  end
  resources :users do
    get :reset_password, :on => :member
    get :edit_password, :on => :member
    post :update_password, :on => :member
    get :list, on: :collection
    get :show_api_key, on: :member
    post :generate_api_key, on: :member
  end

  resources :session do
    get :ao, on: :collection
    get :aologin, on: :collection
    post :aosignin, on: :collection
  end

  resources :book_codes do
    collection do
      post :generate_book_codes
    end
  end

  resources :grades do
    member do
      get :subjects
    end
    resources :subjects do
      resources :courses
      delete :destroy_detail_imgs, on: :member
      get :generate_qr_code_image, on: :member
    end
  end

  resources :static_images do
    collection do
      get :play
    end
  end

  namespace :api do
    namespace :v1 do
      resources :main_page, only: [] do
        collection do
          get :top_video
          get :subjects
        end
      end

      resources :video, only: [] do
        collection do
          get :play
        end
      end

      resources :courses, only: [] do
        collection do
          get :data
        end
      end

      resources :subjects, only: [:show] do
        collection do
          get :check_subject_owner
          get :my_subjects
          get :search
        end
      end

      resources :wechats, only: [] do
        get :wechat_auth, on: :collection
      end

      resources :feedbacks, only: [:create]
      resources :book_codes, only: [:create]
      resources :setting, only: [] do
        collection do
          get :user_agreement
          get :privacy_policy
        end
      end

      resources :text_settings, only: [] do
        collection do
          get :book_code_comment
        end
      end
    end
  end

  resources :customers, only: [:index]
  resources :feedbacks
  resources :text_settings

  post 'areas/cities'
  post 'areas/districts'

  get 'login' => 'session#new', as: :login
  get 'logout' => 'session#destroy', as: :logout

  root 'session#index'
end

app/models/subject.rb
class Subject < ApplicationRecord
  # relationship
  belongs_to :grade
  has_many :courses, dependent: :destroy
  has_many :book_codes, dependent: :destroy
  has_one_attached :courses_page_cover
  has_one_attached :main_page_cover
  has_many_attached :detail_imgs
  has_one_attached :qrcode

  enum subject_type: %i[chinese english math]


  # validates
  validates :code_prefix, length: { is: 2 }, uniqueness: { case_sensitive: false }, format: { with: /\b[A-Z][A-Z]+\b/, message: '只支持大写字母' }, all_blank: false
end

app/controllers/api/v1/subjects_controller.rb
class Api::V1::SubjectsController < Api::V1::BaseController
  before_action :set_customer, only: [:my_subjects, :check_subject_owner, :my_subjects]

  def show
    @subject = Subject.find params[:id]
  end

  def my_subjects
    @subjects = @customer.subjects.group_by(&:grade).sort_by{ |key, _| key.order_no  }
  end

  # 检查当前用户是否拥有当前subject
  def check_subject_owner
    subject_id = params[:subject_id]
    @rs_bool = @customer.subjects.map(&:id).include? subject_id.to_i
    if @rs_bool
      @code = 0
      @message = '您拥有当前课程的权限'
    else
      @code = 1
      @message = '您还没有拥有当前课程的权限，请输入学习码获取.'
    end
  end

  # 搜索分类三种类型
  # 只搜索年级
  # 只所搜科目
  # 年级科目都搜索
  def search
    key_words = params[:key_words]
    @message = '搜索的科目已经成功返回'
    @code = 0
    case key_words.size
    when 3
      grade = Grade.find_by_name(key_words)
      @subjects = grade.subjects
    when 2
      @subjects = Subject.where('name LIKE ?', "%#{key_words}%")
    when 5
      grade_name = key_words[0..2]
      subject_name = key_words[3..4]
      grade = Grade.find_by_name(grade_name)
      @subjects = grade.subjects.where('name LIKE ?', "%#{key_words}%")
    else
      @message = '请检测您搜索的关键词'
      @code = 1
    end

    @subjects = @subjects.nil? ? [] : @subjects.group_by(&:grade).sort_by{ |key, _| key.order_no  }
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  include Wechat
  before_action :set_subject, only: [:show, :edit, :update, :destroy, :destroy_detail_imgs, :generate_qr_code_image]
  before_action :set_grade, only: [:new, :edit, :create, :update, :destroy_detail_imgs, :generate_qr_code_image]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = initialize_grid( Subject, per_page: 20,
                                          order_direction: 'asc',
                                          name: 'subjects' )
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = @grade.subjects.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = @grade.subjects.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to grades_path, notice: '科目已经成功的创建了！' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to grades_path, notice: '科目已经成功的更新了！' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to grades_path, notice: '科目已经成功的删除了！' }
      format.json { head :no_content }
    end
  end

  def destroy_detail_imgs
    @subject.detail_imgs.purge
    respond_to do |format|
      format.html { redirect_to grade_subject_url(@grade, @subject), notice: '科目的详情图片已经删除了！' }
      format.json { head :no_content }
    end
  end

  def generate_qr_code_image
    res = get_qr_code_image 'pages/subject/subject', "subject_id=#{@subject.id}"
    if res["errcode"].nil?
      @subject.qrcode.purge if @subject.qrcode.attached?
      @subject.qrcode.attach io: StringIO.new(res),
                             content_type: "image/jpg",
                             filename: "subject_file_#{@subject.id}"
      return_message = "二维码已经生成！"
      alert_type = 'notice'
    else
      return_message = "二维码生成失败：#{res["errmsg"]}"
      alert_type = 'alert'
    end

    respond_to do |format|
      format.html { redirect_to grade_subject_url(@grade, @subject), alert_type.to_sym => return_message }
      format.json { head :no_content }
    end
  end

  private
    def set_grade
      @grade = Grade.find(params[:grade_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:grade_id,
                                      :name,
                                      :code_prefix,
                                      :order_no,
                                      :description,
                                      :courses_page_cover,
                                      :main_page_cover,
                                      :subject_type,
                                      :main_desc,
                                      detail_imgs: [])
    end
end

app/helpers/api/v1/subjects_helper.rb
module Api::V1::SubjectsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.slim
= simple_form_for([@grade, @subject]) do |f|
  - if @subject.errors.any?
    #error_explanation.alert.alert-warning
      h4
        | 该科目保存时出错：
        = pluralize(@subject.errors.count, "个错误")
      ul
        - @subject.errors.full_messages.each do |message|
          li
            = message
  .form-inputs
    = f.input :name, label: '科目名称'
    = f.input :order_no, label: '顺序号'
    = f.input :code_prefix, label: '学习码前缀', placeholder: '大写字母，两位'
    / = f.input :description, label: '课程简介', as: :text, number: 3
    = f.input :main_desc, label: '主页课程卡片说明'
    = f.input :subject_type, label: '课程类型', as: :select, collection: Subject.subject_type_options, include_blank: false
    small#emailHelp.form-text.text-muted 分辨率(高*宽 单位px)：235 * 330
    = f.input :main_page_cover, label: '主页课程封面', as: :file
    small#emailHelp.form-text.text-muted 分辨率(高*宽 单位px)：678 * 200
    = f.input :courses_page_cover, label: '学习页课程封面', as: :file
    small#emailHelp.form-text.text-muted 分辨率(高*宽 单位px)：auto * 690
    = f.input :detail_imgs, label: '课程详情图片', as: :file, input_html: { multiple: true }
  .form-actions
    = f.button :submit, '确认', class: 'btn btn-success'

app/views/subjects/edit.html.slim
= link_to '返回', grades_path, class: 'btn btn-primary mb-2'
.card
  .card-header
    .card-title 编辑科目
  .card-body
    = render 'form'

app/views/subjects/index.html.slim
h1 Listing subjects

table
  thead
    tr
      th Grade
      th Name
      th
      th
      th

  tbody
    - @subjects.each do |subject|
      tr
        td = subject.grade
        td = subject.name
        td = link_to 'Show', subject
        td = link_to 'Edit', edit_subject_path(subject)
        td = link_to 'Destroy', subject, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Subject', new_subject_path

app/views/subjects/new.html.slim
= link_to '返回', grades_path, class: 'btn btn-primary mb-2'
.card
  .card-header
    .card-title 新建科目
  .card-body
    = render 'form'

app/views/subjects/show.html.slim
.card
  .card-header
    h3.card-title 科目图片
  .card-body
    h5 小程序码
    .row
      = link_to '生成小程序码', generate_qr_code_image_grade_subject_path(@subject.grade, @subject), class: 'btn btn-primary'
    .row
      = link_to '下载程序码', rails_blob_path(@subject.qrcode, disposition: "attachment"), class: 'btn btn-primary mt-2'
    .row
      = image_tag static_url_for(@subject.qrcode), height: :auto, width: '430px'
      

    hr
    h5 主页封面图
    .row
      - if @subject.main_page_cover.attached?
        = image_tag  static_url_for(@subject.main_page_cover), height: :auto, width: '200px'
      - else
        span 暂无

    hr
    h5 学习封面图
    .row
      - if @subject.courses_page_cover.attached?
        = image_tag  static_url_for(@subject.courses_page_cover), height: :auto, width: '200px'
      - else
        span 暂无

    hr
    h5 详情图
    .row
      = link_to '删除详情图', destroy_detail_imgs_grade_subject_path, method: :delete, data: { confirm: '您确认删除吗？' }, class: 'btn btn-danger'
    .row
      - @subject.detail_imgs.each do |img|
        = image_tag  static_url_for(img), height: :auto, width: '200px', class: 'mr-2 mt-2'