config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match "/delayed_job" => BetterDelayedJobWeb, :anchor => false, :via => [:get, :post]

  resources :delayed_jobs
  resources :favorites
  resources :notifications
  resources :sys_configs
  resources :sys_logs do
    get :search, on: :collection
  end

  resources :features do
    get :list, :on => :collection
    get :role_features_grid, :on => :member
    get :add_features, :on => :member
    get :add_features_submit, :on => :member
    delete :remove_feature_from_role, :on => :member
  end

  resources :roles do
    get :role_users_grid, :on => :member
    get :add_users, :on => :member
    get :add_users_submit, :on => :member
    delete :remove_user_from_role, :on => :member
  end

  resources :departments do
    resources :department_docs
    get :department, :on => :member
    get :add_users, :on => :member
    get :add_users_submit, :on => :member
    delete :remove_user_from_department, :on => :member
  end
  resources :users do
    get :reset_password, :on => :member
    get :edit_password, :on => :member
    post :update_password, :on => :member
    get :list, on: :collection
    get :show_api_key, on: :member
    post :generate_api_key, on: :member
  end

  resources :session do
    get :ao, on: :collection
    get :aologin, on: :collection
    post :aosignin, on: :collection
  end

  resources :book_codes do
    collection do
      post :generate_book_codes
    end
  end

  resources :grades do
    member do
      get :subjects
    end
    resources :subjects do
      resources :courses
      delete :destroy_detail_imgs, on: :member
      get :generate_qr_code_image, on: :member
    end
  end

  resources :static_images do
    collection do
      get :play
    end
  end

  namespace :api do
    namespace :v1 do
      resources :main_page, only: [] do
        collection do
          get :top_video
          get :subjects
        end
      end

      resources :video, only: [] do
        collection do
          get :play
        end
      end

      resources :courses, only: [] do
        collection do
          get :data
        end
      end

      resources :subjects, only: [:show] do
        collection do
          get :check_subject_owner
          get :my_subjects
          get :search
        end
      end

      resources :wechats, only: [] do
        get :wechat_auth, on: :collection
      end

      resources :feedbacks, only: [:create]
      resources :book_codes, only: [:create]
      resources :setting, only: [] do
        collection do
          get :user_agreement
          get :privacy_policy
        end
      end

      resources :text_settings, only: [] do
        collection do
          get :book_code_comment
        end
      end
    end
  end

  resources :customers, only: [:index]
  resources :feedbacks
  resources :text_settings

  post 'areas/cities'
  post 'areas/districts'

  get 'login' => 'session#new', as: :login
  get 'logout' => 'session#destroy', as: :logout

  root 'session#index'
end

app/models/role.rb
# -*- encoding : utf-8 -*-
class Role < ApplicationRecord
  has_many :user_roles, dependent: :delete_all
  has_many :users, :through => :user_roles
  has_many :role_features, dependent: :delete_all
  has_many :features, through: :role_features

  validates :name, :presence => true, :uniqueness => true, :length => {:maximum => 50}

end

app/controllers/roles_controller.rb
# -*- encoding : utf-8 -*-
class RolesController < ApplicationController
  layout 'system'
  before_action :set_role, only: [:edit, :update, :destroy, :add_users, :add_users_submit, :remove_user_from_role]
  after_action :make_log, only: [:create, :update, :destroy, :add_users_submit, :remove_user_from_role]

  # 显示角色列表页面，默认显示所有系统角色，并且不需要分页显示
  # 系统在角色列表页面还需要显示“新建角色”按钮，同时针对每一个已有的角色，系统还需要显示“人员”链接和“编辑角色”、“删除角色”按钮。
  def index
    if (SysConfig.super_roles & @current_user.roles.map{ |r| r.name }).empty?
      @roles = Role.where(orgnization_name: [@current_user.orgnization_name, '系统'])
    else
      @roles = Role.all
    end
    @role = params[:role_id] ? Role.find_by_id(params[:role_id]) : @roles.first
    @users = initialize_grid(@role.users, order: 'sort_no', order_direction: 'asc',per_page: 20, name: 'role_users')
  end

  # 显示新建角色表单页面。 
  def new
    @role = Role.new
  end

  # 管理员点击角色列表页面中针对某一 角色的“编辑角色”按钮，系统显示该角色的编辑表单页面。
  def edit
  end

  # 在新建角色页面中，用户点击“提交”按钮，系统保存该角色并返回角色列表页面。
  def create
    @role = Role.new(role_params)
    if (SysConfig.super_roles & @current_user.roles.map{ |r| r.name }).empty?
      @role.orgnization_name = @current_user.orgnization_name
    end

    respond_to do |format|
      if @role.save
        format.html { redirect_to roles_path, notice: '该角色已经成功创建！' }
        format.json { render :index, status: :created}
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # 管理员修改该角色的信息之后，点击“保存”按钮，系统保存该角色修改后的信息并返回角色列表页面。
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to roles_path, notice: '该角色已经成功保存！' }
        format.json { render :index, status: :ok}
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # 管理员点击角色列表页面中针对某一角色的“删除角色”按钮，系统弹出对话框要求用户进行确认，
  # 在管理员确认之后，系统删除该角色并返回角色列表页面。
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: '该角色已经被删除了！' }
      format.json { head :no_content }
    end
  end
    
  # 管理员在角色人员列表页面中，点击 “加入”按钮,系统显示所有人员的列表
  def add_users
    if (SysConfig.super_roles & @current_user.roles.map{ |r| r.name }).empty?
      @users = initialize_grid( User, per_page: 50,
                                conditions: { orgnization_name: @current_user.orgnization_name },
                                order: 'sort_no', order_direction: 'asc',
                                name: 'users' )
    else
      # @users = initialize_grid(User, per_page: 20, name: 'users')
      @users = initialize_grid( User, per_page: 50,
                                order: 'sort_no', order_direction: 'asc',
                                name: 'users' )
    end
  end
  
  # 管理员通过姓名的关键字模糊搜索对列表进行过滤，然后选择某一个人员，点击“加入”按钮，系统将该人员加入该角色，并返回人员列表页面。
  def add_users_submit
    if params[:users] && params[:users][:selected]
      @selected = params[:users][:selected]
      @selected.each do |uid|
        @role.user_roles.find_or_create_by user_id: uid, role_id: @role.id
      end
    end
    redirect_to roles_path(role_id: @role.id), notice: "新的用户已经加入了该角色！"
  end
  
  # 管理员在角色人员列表页面中，针对某一个人员点击“移除”按钮，系统在要求管理员确认之后，将该人员移出该角色，并返回人员列表页面。
  def remove_user_from_role 
    @role.user_roles.where(user_id: params[:user_id]).take.destroy
    @users = initialize_grid(@role.users, per_page: 20, name: 'role_users')
    respond_to do |format|
      # format.html { render :role_users_grid }
      format.html { redirect_to roles_path(role_id: @role.id) }
      format.js
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def role_params
    params.require(:role).permit(:name, :description)
  end
end

app/helpers/roles_helper.rb
# -*- encoding : utf-8 -*-
module RolesHelper
end

app/views/roles/_add_users_grid.html.erb
<%= grid(@users, hide_submit_button: true, hide_reset_button: true, show_filters: :when_filtered) do |g|
  g.action_column html_check_box: false, html: {style: "width:80px;"} do |user|
    @role.users.find_by(id: user.id).nil?
  end

  g.column name: '登录名', attribute: 'login' do |user|
    user.login
  end

  g.column name: '真实姓名', attribute: 'name', ordering: false do |user|
    user.name
  end

  # 平台管理员只关注用户的机构级别的信息
  if admin?
    g.column name: '所属机构', attribute: 'organization_id', ordering: false,
             custom_filter: Organization.all.map{ |organization| [organization.name, organization.id] }, allow_multiple_selection: false do |a|
      a.organization.name if a.organization
    end
  else
  # 机构管理员只关注用户的科室级别的信息
    g.column name: '所属科室', attribute: 'department_id', ordering: false,
             custom_filter: @current_user.organization.departments.map{ |department| [department.name, department.id] }, allow_multiple_selection: false do |a|
      a.department.name if a.department
    end
  end

  g.column html: {style: "width:20px;"} do |user|
  end
end -%>

app/views/roles/_form.html.slim
= simple_form_for(@role, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
  - if @role.errors.any?
    #error_explanation.alert.alert-warning
      h4
        | 该角色保存时出错：
        = pluralize(@user.errors.count, "个错误")
      ul
        - @user.errors.full_messages.each do |message|
          li
            = message
  .form-inputs
    = f.input :name, label: '角色名称'
    = f.input :description, label: '角色描述', as: :text, :input_html => {:rows => 5}
  .form-actions
    = f.button :submit, '确认', class: 'btn btn-success'

app/views/roles/_role_users_grid.html.erb
<div class="row">
  <div class="col-sm-12">
    <h4 class="h4">该角色所拥有的用户</h4>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="btn-group btn-group-sm" role="group" aria-label="...">
      <button class="btn btn-primary btn-sm wg-external-submit-button" data-grid-name='role_features'>过滤</button>
      <button class="btn btn-secondary btn-sm wg-external-reset-button" data-grid-name='role_features'>清除过滤条件</button>
    </div>
    <span>
      <%#- if can?("roles", "add_users") && can_sys?(role) %>
      <%- if can?("roles", "add_users") %>
        <%= link_to '增加人员', add_users_role_path(role), class: "btn btn-primary btn-sm pull-right" %>
      <%- end %>
    </span>
  </div>
</div>
<br>
<div class="table-responsive">
  <div class="row">
    <div class="col-sm-12">
      <%= grid(users, hide_submit_button: true, hide_reset_button: true, show_filters: :when_filtered) do |g|
        g.column name: '登录名', attribute: 'login' do |user|
          user.login
        end

        g.column name: '真实姓名', attribute: 'name', ordering: false do |user|
          user.name
        end

        g.column in_csv: false, html: {style: "width:30px;"}  do |user|
          if can?("roles", "remove_user_from_role") && can_sys?(role)
            link_to '移除用户', remove_user_from_role_role_path(role, user_id: user.id), method: :delete, data: { confirm: '您确认移除该用户吗？' }, class: 'btn btn-danger btn-sm'
          end
        end
      end -%>
    </div>
  </div>
</div>

app/views/roles/add_users.html.slim
.row
  = link_to '返回', roles_path, class: "btn btn-primary mb-2"
  .card
    .card-header
      h3.card-title 为角色增加用户
    .card-body
      = form_tag "/roles/#{@role.id}/add_users_submit", method: :get do |f|
        .row
          .col-sm-12
            .btn-group.btn-group-sm role="group" aria-label="..."
              button.wg-external-submit-button.btn.btn-primary data-grid-name="users" 过滤
              button.wg-external-reset-button.btn.btn-secondary data-grid-name="users" 清除过滤条件
            | &nbsp;
            .btn-group.btn-group-sm role="group" aria-label="..."
              - if can?("roles", "add_users_submit")
                = submit_tag '增加所选用户', class: "btn btn-primary btn-sm"
            | &nbsp;
            span.h5
              | 当前角色：
              = @role.name
        br
        .row
          .col-sm-12
            .table-responsive
              = render "add_users_grid"

app/views/roles/edit.html.slim
.row
  = link_to '返回', roles_path, class: 'btn btn-primary mb-2'
  .card
    .card-header
      h3.card-title 编辑角色
    .card-body
      = render 'form'

app/views/roles/index.html.slim
.row
  .card
    .card-header
      h3.card-title 用户角色管理
      - if can?("roles", "new")
        = link_to '新建角色', new_role_path, class: "btn btn-primary", style: 'margin-left: auto'
    .card-body
      .row
        .col-md-6
          .table-responsive
            table.table-hover.table-outline.table-vcenter.text-nowrap.card-table
              thead
                tr
                  th 角色名称
                  th 角色描述
                  th
              tbody
                - @roles.each do |role|
                  tr id="role-#{role.id}" class="#{'info' if role == @role}"
                    td style="width: 120px"
                      = role.name
                    td
                      = h(role.description)
                    td.text-center
                      - if can?("roles", "index")
                        = link_to '查看', roles_path(role_id: role.id), class: 'btn btn-secondary btn-sm mr-1'
                      - if can?("roles", "edit") && can_sys?(role)
                        = link_to '编辑', edit_role_path(role), class: 'btn btn-secondary btn-sm mr-1'
                      - if can?("roles", "destroy") && can_sys?(role)
                        = link_to '删除', role, method: :delete, data: {confirm: '您确认删除吗？该角色所拥有的用户也同时失去与该角色的关联(用户本身并不删除)。'}, class: 'btn btn-danger btn-sm mr-1'
        .col-sm-6
          = render partial: "role_users_grid", :locals => {role: @role, users: @users}

app/views/roles/new.html.slim
.row
  = link_to '返回', roles_path, class: "btn btn-primary mb-2"
  .card
    .card-header
      h3.card-title 新建角色
    .card-body
      = render 'form'